spring.application.name=Weather-App
weather.api.key=${WEATHER_API_KEY:b09ccde6ecc04551811212248260501}
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json
